FROM fusuf/whatsasena:latest
https://github.com/white-devil-gits/VEDIKETTU-JAANU-2.0 /root/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
ENV TZ=Europe/Istanbul
RUN npm install supervisor -g
RUN yarn install --no-audit

CMD ["node", "bot.js"]
